### PR TITLE
Fix issue with undefined values in the grid

### PR DESCRIPTION
**Pull request by theduckylittle**
`undefined` was not a supported value by the mapbox filter
generator. This updates the query to force undefined to become
`''` (an empty string).

refs: #697

### CODE REVIEW

**Comment by chughes-lincoln** [comment]
I'm still getting this error when I rebuilt the demo on this PR.
This time the null values show as (empty). Trying to uncheck the null features fails
fails, and hitting 'Set' causes the map to crash.

**Comment by theduckylittle** [comment]
Try this update! Took an alternative approach to generating the list options.

**Comment by klassenjs** [comment]
@chughes-lincoln Are your interesting errors caused by this PR or is it a separate bug?

**Comment by chughes-lincoln** [comment]
It's probably a separate, related bug. Though it only seems to manifest itself when there's a null value in the selection set.
Any case where I can replicate it on this PR would also fail on the demo because there's a null value.

**Pull request merged**
