### PR TITLE
Added opacity controls!

### PR DESCRIPTION
**Pull request by theduckylittle**
New FadeTool and UnfadeTool along with all the necessary
supporting changes.

Supports: https://github.com/geomoose/gm3/issues/45

### CODE REVIEW

**Comment by klassenjs** [comment]
Code looks good and test good.  Do you want to add it to the example mapbook before merging?

**Comment by theduckylittle** [comment]
I didn't know what a good example would be? I used the AGS layer for testing.  Obviously, adding it as an example would be a good idea but I didn't really know which layer to "pick".

**Comment by theduckylittle** [comment]
Maybe just throw it on the sketch layer since it has the full spread anyway?

**Comment by klassenjs** [comment]
It doesn't have to be one layer.  Personally my choice would be add it to all the backgrounds to fade between them.

**Comment by theduckylittle** [comment]
Added examples to the set of background layers.

**Pull request merged**
