### PR TITLE
Signal a definite way to end interacting with the map

### PR DESCRIPTION
**Pull request by theduckylittle**
This is addressing ticket #60 .  It presents the user with a way to stop whatever tool is open.

Definitely some room for improvement.  If there's no major functionality objections I'd like to see this merged so that we can start the feedback cycle on it. (Specifically, I'd like @elil 's eyes on this one.)

### CODE REVIEW

**Comment by klassenjs** [comment]
Draw tools aren't working for me with this PR.  I am seeing `i.append is not a function` in the console.

**Comment by klassenjs** [comment]
Looks like the error is in createStopTool at elem.append(button);

**Comment by elil** [comment]
This looks great.  It seems mostly oriented towards "drawing" (or "Selection of existing drawings").  It seems to only apply to the drawing phase of tools that have drawing phases (Measure, Identify, Select Features).  When these tools are not in a drawing phase (like when none of the drawing tools are engaged), there is is no "End" option.  

This emphasis on drawing is probably why it says, "End Drawing" (or "End Selection").  Although this is technical correct and very articulate, "Cancel" might be a more universally understood message.

Ending interaction (or "Cancel") may be expandable to other non-drawing or non-selection of existing drawings tools (Search, non-drawing phases of Measure, Identify, Select Features, etc).  

See also #81, for general tab interaction and how this may tangentially relate to this.

**Comment by theduckylittle** [comment]
@klassenjs Do you have any objections to changing to the constant "Cancel" button instead of more detail? I'm okay with "Cancel" instead of the smart text.  In a non-pushed version of the code I was actually putting the draw tool name in the "stop" button but quit that.  "Cancel" does seem nice and consistent.

**Comment by klassenjs** [comment]
I don't care what the button is labeled on the map.  
But it seems to me the button on the map should be related to things that change the map from the normal interaction and not necessarily a general cancel for anything.  I am unclear on the discussion what the actual scope is being discussed.  (Also IMHO it would be nice if escape key canceled drawing).

**Pull request closed without merging**
