### PR TITLE
Add a scaleline to the print out

### PR DESCRIPTION
**Pull request by theduckylittle**
Draws a scaleline on the PDF when configured
to do so. The settings are the same ones used
to render the scaleline for the map.

refs: #398

### CODE REVIEW

**Comment by klassenjs** [comment]
It looks like the scale is off.  It says 2km, but is really closer to 3km.

image

(Printed, saved, opened in GIMP, relocated the scalebar over the grid).

**Comment by theduckylittle** [comment]
Uh... I'm not seeing the same issue (looking at a 2mi grid).

duck-2mi-grid

**Comment by theduckylittle** [comment]
Another example that 'looks right'...

image

**Comment by klassenjs** [comment]
Figured out how I broke it: Change the print resolution.

**Comment by klassenjs** [comment]
Also found a new bug that confused me in the first place. #421

**Comment by klassenjs** [comment]
Looks good.

**Pull request merged**
