### PR TITLE
CSS tweak to prevent the footer from overflowing.

### PR DESCRIPTION
**Pull request by theduckylittle**
This is an issue that makes itself readily visible in FF on linux.

### CODE REVIEW

**Comment by theduckylittle** [comment]
refs: #178

**Comment by klassenjs** [comment]
Scrollbar is gone.  The drop down is clipped off a bit but still usable.  Good enough?
screenshot from 2017-09-24 18-11-30

**Comment by theduckylittle** [comment]
We could do better but making the footer auto-height but it becomes a pretty deep rabbit hole with trying to prevent overflow into other elements of the UI.

**Comment by theduckylittle** [comment]
so... yeah... this is better... if someone files a follow up looking for perfect / unusable we'll take another step forward. The real solution probably involves dropping the use of the select element as they are rendered VERY different across browsers and platforms.

**Comment by klassenjs** [comment]
It is certainly the lesser of evils.

**Pull request merged**
