### PR TITLE
Updated OSM geocoder.

### PR DESCRIPTION
**Pull request by theduckylittle**
No more major bugs and the points from the search results
will now render on the highlight layer.

### CODE REVIEW

**Comment by theduckylittle** [comment]
refs: #139

**Comment by elil** [comment]
How soon does the demo get built after a merge?

**Comment by theduckylittle** [comment]
< 10 minutes.

**Comment by klassenjs** [comment]
I'll have all 3 of them in another few minutes.

**Comment by klassenjs** [comment]
ac8fd is latest

**Pull request merged**
