### PR TITLE
Reconfigured the grid to support remote templates.

### PR DESCRIPTION
**Pull request by theduckylittle**
1. The new default example uses a remote template for the grid.
2. Grid updated to detect when there is already a parsed object
   in the contents instead of a string.
3. select was changed to also request grid templates as available.
   This is a non-breaking backwards compatible change and the
   behaviour can be reverted by setting showGrid to false in the configuration
   section of select.

refs: #251

### CODE REVIEW

**Comment by klassenjs** [comment]
This undos #265

**Comment by theduckylittle** [comment]
I will merge it with master and repush.

**Comment by theduckylittle** [comment]
fixed

**Comment by klassenjs** [comment]
The interesting thing here is github didn't flag this as a merge conflict (before you resolved it).

Was git smart enough to do the merge (update the json file from the change that first happened in the mapbook) or did you need to fix this manually?

I probably wouldn't have cought the regression if I wasn't testing the PRs back to back.

**Comment by theduckylittle** [comment]
I needed to do it manually. So, good catch!

**Pull request merged**
