### PR TITLE
Consistently buffer point on line/point queries

### PR DESCRIPTION
**Pull request by theduckylittle**
- Refactores the pixel-tolerance code to be less inline with
   the query function.
- Changes the AGS query and the WFS query to both use
   pixel-tolerance as defined in the source. (AGS defaults to 2 as before)

Refs: #601

### CODE REVIEW

**Comment by brentfraser** [comment]
It will take me awhile to configure my test map sources.   I'll work on it over the next couple of days.

**Comment by theduckylittle** [comment]
This should be a fix for #601

**Comment by brentfraser** [comment]
Here's my test results (using https://github.com/geomoose/gm3/wiki/Mapbook-for-testing-server-connections):

P = Pass (success)
F = Fail (expected results not returned)
E = Error (console shows GM crash)
```
	Vector with Feature Info
		Vector
			Sketch
F				Points
F				Lines
P				Polygons
		GeoJSON
P			GeoJSON Polygons
		WFS
P			WFS Polygons
N/A			WFS Lines (Test Vector Reprojection)
		Mapserver WFS
P			Mapserver WFS Polygons
		AGS FeatureServer
E			AGS FeatureServer Points
E			AGS FeatureServer Lines
E			AGS FeatureServer Polygons
		AGS MapServer
E			AGS Vector Points
E			AGS Vector Lines
E			AGS Vector Polygons

	Image with Feature Info (inc. vector geom)
		Mapserver
P			Mapserver Points
P			Mapserver Lines
P			Mapserver Polygons 
		WMS
F			WMS Polygons (Duluth)
		AGS
F			AGS Image Labels (Minneapolis)
F			AGS Image Polygons (Minneapolis)
```

**Comment by theduckylittle** [comment]
The AGS vector services should now be fixed.

Other interesting finds (likely for follow up tickets):
1. ESRI does not return proper GML from a WMS GetFeatureInfo request.
2. We do not have any query handlers for raster AGS services. Those layers, according to GeoMoose, are not queryable.
3. The sketch layer (geojson) should really identify properly. I want to fix that quirk.

**Comment by brentfraser** [comment]
Much better!
```
		AGS FeatureServer
P			AGS FeatureServer Points
P			AGS FeatureServer Lines
P			AGS FeatureServer Polygons
		AGS MapServer
P			AGS Vector Points
P			AGS Vector Lines
P			AGS Vector Polygons
```

**Comment by brentfraser** [comment]
I've added some .geojson files to the demo-data https://github.com/geomoose/gm3-demo-data/pull/8
And updated the mapbook-testing.xml https://github.com/geomoose/gm3/wiki/Mapbook-for-testing-server-connections

Note the geoJSON files have `null ` property values which cause the property dialog to fail.

**Comment by brentfraser** [comment]
@theduckylittle you commented above:
"We do not have any query handlers for raster AGS services. Those layers, according to GeoMoose, are not queryable."

Is this new?  My notes show  "The layer on the AGS server must be configured to have "Supported Operations: Query" , but I can't recall if I actually got Identify to work on such a layer in my previous testing.

For a sample data source have a look at https://gis2.co.dakota.mn.us/arcgis/rest/services/DCGIS_OL_Transportation/MapServer/21

**Comment by brentfraser** [comment]
Hmm.  Looks like my previous testing notes on the subject were "aspirational".  While AGS supports it, it is not (and never has been) implemented in GeoMoos.

**Pull request merged**
