### PR TITLE
Fix for Identify

### PR DESCRIPTION
**Pull request by theduckylittle**
- Giant pile of React/Redux fixes
- Fixes the broken identify.

Refs: #323

### CODE REVIEW

**Comment by klassenjs** [comment]
This may be a different case, but I am still seeing #323 like behavior with:

1) Open GeoMoose
1) Turn off all layers on visible tab
1) Identify, click point

**Comment by theduckylittle** [comment]
That was the exact behaviour I was testing with...

**Comment by klassenjs** [comment]
Miss an add/push?

**Comment by klassenjs** [comment]
I'm on dbc956b

**Comment by klassenjs** [comment]
Tested with:
```
rm -rf dist coverage node_modules
npm install && grunt build
```

**Pull request merged**
