### PR TITLE
Update to ol-mapbox-style

### PR DESCRIPTION
**Pull request by theduckylittle**
Previous Mapbox GL to OL style library was deprecated.
This new version is more full featured. Updated the
vector layer class to also check the spec for divving up
the properties between paint and layout sections.

### CODE REVIEW

**Comment by klassenjs** [comment]
Are there any backwards compatibility issues here?

**Comment by theduckylittle** [comment]
Not as far as I can tell:
1. I patched them using the paint vs layout detection.
2. All of our internal query functions used the query functions from `util.js` which wraps and normalizes the queries.
3. All of the layers in the demo appear to work with no changes.

**Comment by theduckylittle** [comment]
oh, and 4. It's all implementing version 8 of the MapBox GL spec. So it should all be compatible.

**Comment by klassenjs** [comment]
I'm getting `et.setRotateWithView is not a function` in the production build on FF when drawing in the Drawing and Markup layer (polygon and point tested).

**Comment by theduckylittle** [comment]
Did you wipe node_modules?

**Comment by klassenjs** [comment]
Yep, twice.

**Comment by theduckylittle** [comment]
Updated the package.json to spec OL6. It must've been my own messed up node_modules!

**Comment by klassenjs** [comment]
Identify is broken.  Identify.  Click on a parcel.

Blank map.  0 Features/1 Layer/Spinny arrows.  Errors in console.
`Unhandled promise rejection TypeError: "c.getGetFeatureInfoUrl is not a function"`

**Comment by theduckylittle** [comment]
Identify should now be fixed. Actually was an issue with any point-styled selection.

**Comment by klassenjs** [comment]
Looks good except for the failing test.

**Pull request merged**
