### PR TITLE
Fix for high resolution print

### PR DESCRIPTION
**Pull request by theduckylittle**
1. Fixes the canvas selector based on the OpenLayers demo code
   and tweaks from robinrullo.
2. Refactors and cleans up components for print.
3. Adds a progress bar which is handy for when big images
    are coming in over the pipe.

refs: #640

### CODE REVIEW

**Comment by robinrullo** [comment]
I think that only printing the first layout works: the exportSize of getImage seems to not be updated when another layout is selected. I tried printing page-letter-portrait, the map size is good but the canvas size is not. 

To reproduce, select page-letter-landscape (without legend because the map size format of page-letter-landscape-legend is similar as portrait), close modal, reopen print (that will set the canvas size to page-letter-landscape-legend format) and then select page-letter-portrait, you will see that: 
image
image

**Comment by theduckylittle** [comment]
Found it! There was an issue with the map-rendering callback creating a closure.

**Comment by robinrullo** [comment]
There is another issue!
To reproduce, just change the size of the browser window (or open console does the trick) when you are in printmodal.
image
image

**Comment by theduckylittle** [comment]
Thanks for the great testing work on this!

I wasn't able to recreate the state error bug but I was able to recreate an infinite loop. A "test fix" I did last night was causing an issue. The last commit should fix it. If you're having problems on your latest build, let me know.

**Comment by robinrullo** [comment]
Everything seems to be working fine now 😃
There is just one thing (I don't know if it's done on purpose), the printpreview no longer adapts to the canvas size.

Before: 
image

Now:
image

Glad I can help improve the app  !

**Comment by theduckylittle** [comment]
And now that is fixed too.

**Comment by robinrullo** [comment]
I accidentally opened/closed very quickly the modal when the map was still being rendering in the preview and got the same state error than before

**Comment by theduckylittle** [comment]
Oy! Okay. I think I got it for real, finally, completely this time. I wrapped the `setImage` call in a check to make sure the `parentRef` still existed.

**Comment by chughes-lincoln** [comment]
I rebuilt the demo on this PR and so far I'm not seeing any of the errors that were mentioned. It successfully fixes the issue of certain layers (sketches, some basemaps) not appearing in the print preview or the print out when using certain high resolution monitors. 

The only odd thing is that I haven't been able to get that progress bar that you mentioned to show.

**Pull request merged**
