### PR TITLE
UX Updates for Editing Tools

### PR DESCRIPTION
**Pull request by theduckylittle**
1. Clean up rendering logic for drawing tools.
2. Move the drawing tools to the map from the catalog.
3. Create a "edit trigger" from the catalog.
4. Allow adding classes to catalog layers and add an inline tools style.
5. Additional clean up of catalog layers
6. Better wording for opening the drawing tools + translation

### A single "edit" tool

image

### Opens a toolbar on the map

image

### With a tool selected, show the stop sign

This collapses down to just the stop sign. Then returns back to the toolbar when "stop" has been clicked.

image

refs: #636

### CODE REVIEW

**Comment by brentfraser** [comment]
Is there more to come?  The Stop button doesn't actually save the edits, etc.

**Comment by theduckylittle** [comment]
It never did?

This hasn’t changed the behavior of any of the tools.

**Comment by brentfraser** [comment]
How do I save my edits?

**Comment by brentfraser** [comment]
Are we missing the "Save" and "Undo" buttons?

**Comment by robinrullo** [comment]
You mixed up the keys used for paths but I think to draw, you use `activeSource` and to then edit the feature, you use `editPath`.
There is used `editPath`: https://github.com/geomoose/gm3/blob/bd06cf76f36ee6575e718fd523f404ee3f69d0ba/src/gm3/components/catalog/tools/edit-tool.js#L48
and then is `activeSource` instead of `editPath`:
https://github.com/geomoose/gm3/blob/bd06cf76f36ee6575e718fd523f404ee3f69d0ba/src/gm3/components/map/index.js#L1328

So Drawing from `Drawing and Markup`, is drawing to selection layer (activeSource = '' => path = null => selection layer).

**Comment by theduckylittle** [comment]
Oopsy doodle. 

I see where I messed up, I had forgotten to pass in the active source when changing the draw tools. Things look to be working more properly now!

**Comment by brentfraser** [comment]
Much better.  Is there someway we can enforce "the-layer-must-be-on-to-edit".  Otherwise strange things happen.

**Comment by brentfraser** [comment]
Or just exit the edit tools when the layer is turned off.  (Warn if there are pending edits?)

**Comment by theduckylittle** [comment]
Done and done. The user can still hurt themselves by turning off the layer while editing. I'm willing to ticket that for follow up work if folks really think it'll be an issue.

**Comment by klassenjs** [comment]
This has some strange interactions with the select tool.

Edit Drawing and Markup.  Add a Polygon (doesn't really matter what)
Select (note don't click stop)
Can draw stuff normally for select
Click Stop
Now the Select tool and the Drawing and Markup tool (on map) are linked (changing tools on the select tab or map seem to change the other)
Now draw something (seems to go to the Drawing and Markup layer if picked the tool from the map and goes to the select tool geom if picked the tool from the tab.)

**Comment by brentfraser** [comment]
@theduckylittle  Re edit tool in catalog.  Can we move the edit tool to be to the left of the favourite tool (so between the fav tool and the layer name).  That way we could get rid of the white space caused by having the edit tool on a separate line/div.

**Comment by klassenjs** [comment]
Continued in #681

**Pull request merged**
