### PR TITLE
Adding a DOI badge to the README.md

### PR DESCRIPTION
**Pull request by tchaddad**

### CODE REVIEW

**Comment by jmckenna** [comment]
great, thanks @tchaddad !

**Comment by jmckenna** [comment]
cc @ploewe

**Comment by klassenjs** [comment]
I see geomoose-website was already updated.

**Comment by jmckenna** [comment]
I have added to the wiki list.

**Comment by jmckenna** [comment]
you're absolutely correct @klassenjs we should always use the persistent DOI, 7976084 (I've updated the wiki)

**Comment by klassenjs** [comment]
I can login to the OSGeo Wordpress, but I can't find where to edit the project info to add the DOI.

**Comment by ploewe** [comment]
Dear Jeff, dear Jim, dear geomoose community,

 

congratulations to minting a persistent software DOI for the geomoose project !

 

Maybe of interest: If members of the development team should have registered an ORCID (a persistent ID for persons), these personal IDs can be linked by the DOI to the software releases for automated updates (and due credit), whenever there's a new software release. PROJ picked up this practice using this earlier this year. Latest info here: https://doi.org/10.5281/zenodo.7889326 (slide 10).

 

Best,

Peter

 

***@***.***>

 
 

Gesendet: Samstag, 27. Mai 2023 um 14:32 Uhr
Von: "Jeff McKenna" ***@***.***>
An: "geomoose/gm3" ***@***.***>
Cc: "Peter Löwe" ***@***.***>, "Mention" ***@***.***>
Betreff: Re: [geomoose/gm3] Adding a DOI badge to the README.md (PR #836)


 

cc @ploewe

**Comment by klassenjs** [comment]
@jmckenna @ploewe Do you know how we can add the DOI badge to our OSGeo Project page? (slide 8)   I can't find the right spot to edit that on the OSGeo Wordpress.  When I try to edit the project I see the checklists, but where it looks like the project text should go is blank.

**Pull request merged**
