### PR TITLE
Tweaks to improve the build speed of the JS.

### PR DESCRIPTION
**Pull request by theduckylittle**
Trying to make fire.

### CODE REVIEW

**Comment by klassenjs** [comment]
`grunt build` hangs on Win7 in webpack:build-dev at 61% 390/456 build modules.

0% CPU usage, no disk, usage, plenty of free memory.

**Comment by theduckylittle** [comment]
As we're basically ignoring the source maps for "index" right now, maybe we just drop building that.  It saves quite a bit of time on the build-deploy.  That alone might make the process less onerous.

**Comment by klassenjs** [comment]
I am curious how much time and RAM that would save.

It would be cool if the source maps worked in production for debugging, but I have never figured them out (maybe a Firefox thing).  So what I am trying to say is right now I wouldn't notice their absence.

**Comment by klassenjs** [comment]
Note: It looks like UglifyJS uses the source map in deploy to give line numbers in errors/warnings.

**Comment by theduckylittle** [comment]
closing for further research elsewhere.

**Pull request closed without merging**
