### PR TITLE
Fix for broken zoom-to icons, refs: #96

### PR DESCRIPTION
**Pull request by theduckylittle**
Ensures the extent is properly processed.

### CODE REVIEW

**Comment by CaitW** [comment]
This also fixes the currently broken "zoom to full extent" tool.

**Comment by klassenjs** [comment]
A small nit: the zoom-to seems to be zooming based on the map if the grid wasn't there (i.e. the bottom of the features seem to be cut off).  Your call if this should be fixed or not.

@theduckylittle I'm not sure how the Zoom to Full Extent tool is currently broken (it appears to zoom to MN from the toolbar, and work correctly on the Drawing and Markup layer to me) but do you want to add @CaitW 's fix to this?

**Comment by theduckylittle** [comment]
That's fine with me.  With the OL4 upgrade, there are going to be subtleties that get missed.

**Comment by klassenjs** [comment]
Confused: I am waiting for commits or merging?

**Comment by theduckylittle** [comment]
Sorry, I'll make the change and push (5 minutes).

**Comment by theduckylittle** [comment]
pushed.

**Pull request merged**
