### PR TITLE
OpenLayers 5 Upgrade, Tests no longer require canvas

### PR DESCRIPTION
**Pull request by theduckylittle**
1. Upgrade to OpenLayers 5.
2. Map tests are skipped when `node-canvas` is not present.

### CODE REVIEW

**Comment by klassenjs** [comment]
I am seeing test failures with canvas installed.  I haven't dug into this yet.

```
Error: Not implemented: HTMLCanvasElement.prototype.getContext (without installing the canvas npm package)
```

**Comment by klassenjs** [comment]
Not sure if I am not seeing the same version of things, but Select Features is failing, and measure is returning an empty tab instead of measurements.

**Comment by klassenjs** [comment]
Search parcel is failing too..... The only think I see that I can make sense of is `this.mapDiv is null`

**Comment by theduckylittle** [comment]
You shouldn't be seeing that error on the latest branch... the getContext is polyfilled... on a clean directory I don't have a problem.

**Comment by klassenjs** [comment]
I cleaned all the stuff in gm3, unless it is in `~/.node-hides-stuff-in-silly-spots`.

**Comment by klassenjs** [comment]
Things look good with the latest push.

**Comment by elil** [comment]
Wow, nice work! :+1:

**Pull request merged**
