### PR TITLE
More coverage

### PR DESCRIPTION
**Pull request by theduckylittle**
Major push to get more tests integrated into the UI.

### CODE REVIEW

**Comment by theduckylittle** [comment]
@klassenjs This is the promised testing update I threatened to write.

**Comment by klassenjs** [comment]
Travis says toolbar is broken.

**Comment by theduckylittle** [comment]
I think that's because of a mid run recommit. If you look up in the list, Travis finished fine and the change wouldn't have effected test output.

**Comment by klassenjs** [comment]
It did test ok locally.

I'm not sure about the explanation.  I haven't known travis to update the files mid test.  The log on travis shows it did complete, but with one a failed test.  It isn't like it was interrupted.

I wonder if it has to do with node versions.

**Comment by theduckylittle** [comment]
Yes but look at the difference between commits. The first one passed and seconds later I pushed another that corrected a file *that does not affect the tests.* So there's some weirdness going on.

**Comment by klassenjs** [comment]
Sorry, it has been a busy day.  Ok, I see that.... If it is a legit problem it will show up on the next one.

**Comment by klassenjs** [comment]
Tests passed in master.

**Pull request merged**
