### PR TITLE
Upgrading to OL 4.4 and React 16

### PR DESCRIPTION
**Pull request by theduckylittle**
1. upgraded the lib deps in package.json
2. fixed tests

Will clear the WIP flag once I'm happy with how the tests are processing.

### CODE REVIEW

**Comment by theduckylittle** [comment]
Test setup has been updated, everything passing, no reduction in coverage.

**Comment by theduckylittle** [comment]
refs: #234

**Comment by klassenjs** [comment]
Still needs the canvas hack for tests to pass.

**Comment by klassenjs** [comment]
I'm getting an odd error in FF/Linux in production.

```
GET 
http://localhost/~jimk/gm3/examples/desktop/site.css [HTTP/1.1 404 Not Found 0ms]
Error: shallow renderer is not available in production mode.  geomoose.min.js:102:31112
ReferenceError: gm3 is not defined[Learn More]
```

**Comment by theduckylittle** [comment]
I have found a hackier canvas modification but any tests that require comparing the contents returned from a rendered canvas will not pass. As we're not testing OpenLayers this might be a worthwhile alternative.

**Pull request merged**
