### PR TITLE
Add client side buffering!

### PR DESCRIPTION
**Pull request by theduckylittle**
Change summary:

1. Adds JSTS dependency.  Unlike previous versions this exercises the new ES6 modules available for JSTS.  So while similar to the OL4 upgrade this does add to the build time it is now only pulling from JSTS what it really needs.  A more ambitious project (much later date) would be to pull the geometry models out of JSTS and create ones based on the openlayers geometries.  For now, we are using GeoJSON as a pass-through transport between JSTS/OpenLayers/GeoMoose.

2. I placed the buffering functionality into a dedicated JSTS module.  If someone really never needed the buffer capability then they could actually fork GeoMoose with a removed gm3.jsts and scrub the necessary functions from the map component and they could move on without that dependency.  Naming the gm3 module after the dependency breaks the tradition of "abstracting" functionality but as this could be a very large dep I wanted to make sure all of it's code was fairly isolated and obvious.

3. There is a new set of actions for handling buffers.  The buffer is actually set in the Map's state.  The map checks it for a non-zero value and then buffers the shape appropriately.

4. A "selection/selection" layer was added similar to the results layer.  This is handled internally as a display layer for the map's selection features.  It functionally works as a "preview" layer for the user's selection.  Word of warning: both the results/* layers and the selection/* layers do not have obvious user controls.  So when using HashTrack you can get the application into a bit of an odd state where the highlight/preview layers are off and they cannot be turned on.  I plan to file a follow up issue as to how that could be resolved.  It probably merits discussion with @klassenjs .

5. While "multipoint" is no longer broken (See issue #82 ) it has some odd behaviours that may not be expected when applying buffers.  I believe that JSTS is handling MultiPoint as a degenerate case and is only buffering the first point. 

6. Services are now configured with a "bufferAvailable" attribute.  When set to true, the buffer functionality will appear.

I think I've written almost as many lines as there is code in the PR. While it sounds like a big change the substantive code changes aren't that huge.

### CODE REVIEW

**Comment by theduckylittle** [comment]
Just to get the cross tagging, this implements #48

**Comment by klassenjs** [comment]
My thought is internal layers should be somehow identified (either by class or by flags of what actions are appropriate) so various UI components can decide how to deal with them (ignore, don't allow to turn off, don't allow zindex change)

**Comment by klassenjs** [comment]
I might be missing something, but I don't see the setting the buffer doing anything on Select Features.  Win/Chrome/index.html

**Comment by theduckylittle** [comment]
Like it's because you switched branches and didn't delete your hash

**Comment by klassenjs** [comment]
Can you change the buffer after you draw or only before?

With a point and a 9mi buffer, I got it into a state where I couldn't draw anything else and the buffer wouldn't clear the screen when exiting the tool.

**Comment by klassenjs** [comment]
There are a lot of gremlins here.

Buffer 100 ft, select a polygon from Drawing Layer, change buffer to 2000ft, go to measure line - measure buffer as closer to 150ft, go back to select features, buffer is set at 0, draw line, line is buffered (at about 100-150ft).  (Note buffer and selected shape also stayed while switching tools).

**Comment by klassenjs** [comment]
(cont) go back to measure tool... all the measurements are buffered on the map.

**Comment by elil** [comment]
In regard to above point, 5. Multi-point buffer, it appears to only buffer the most recent (i.e. last, not first) point.

**Comment by elil** [comment]
This does not preserve (and display) the original input geometry but rather transforms the input geometry to the buffered geometry.  Showing both might be better.

**Comment by elil** [comment]
@klassenjs pertaining to your above comment (not sure how to reply to specific comment), did you enroll in the "How to be an 'average' user" class by me?  That is some crazy testing but good to put it through its paces.

**Comment by klassenjs** [comment]
@elil I haven't, but I was exploring possible failure modes based on the code and past problems.

Responding to the bug reports in #107 since this has been merged.

**Pull request merged**
