### PR TITLE
World's First Javascript + GeoPDF maker.

### PR DESCRIPTION
**Pull request by theduckylittle**
Woot.

refs: #229

### CODE REVIEW

**Comment by klassenjs** [comment]
That's slick.  Tested PDFs in QGIS and Avenza.  Tested printing on Firefox and Chrome/Android.

It generally works, but I don't want to push it to master yet because there is a non-uniform vertical shift in the coordinates across the print.  I tested with a 1°x1° lat,lon grid generated in QGIS and uploaded into the GeoMoose Drawing Layer.  The grid intersections appear to match up the coordinate display within GeoMoose.

[grid.geojson.gz](https://github.com/geomoose/gm3/files/1370053/grid.geojson.gz)

Printing the grid gives:
[print_1507590356439.pdf](https://github.com/geomoose/gm3/files/1370061/print_1507590356439.pdf)

Then overlaying the print and the orig grid in QGIS gives (print orange, orig grid black):
grid-compare

[grid-compare.jgw.txt](https://github.com/geomoose/gm3/files/1370062/grid-compare.jgw.txt)

**Comment by theduckylittle** [comment]
With QGIS set to print in 3857, does the shift still exist?

**Comment by klassenjs** [comment]
Yes. Both grids warp equally.

**Comment by klassenjs** [comment]
Status update: Dan and I have been working on this and we are still seeing the shift in the middle and suspect we can't fib about 4326 vs 3857.  This means we need to figure out how to get things to grok 3857.

**Comment by klassenjs** [comment]
Looks like geo-referencing is correct across resolutions and page sizes now.

**Comment by theduckylittle** [comment]
AWESOME!!! I'm like holy s**t excited for this merge! Woot!!!

**Comment by elil** [comment]
👍

**Pull request merged**
