### PR TITLE
Add support for `always-on` layer.

### PR DESCRIPTION
**Pull request by theduckylittle**
This implementaiton uses a "param" of "always-on",
this will let administrators specify their own layers
as never being able to be turned off.

Refs: #89

### CODE REVIEW

**Comment by klassenjs** [comment]
Is always-on accessible from the mapbook?

**Comment by theduckylittle** [comment]
Yes. But the built-in layers have it set by default.

Mapbook syntax:
<Param name="always-on">true</param>

**Comment by klassenjs** [comment]
I can't get the mapbook part to work.  I'm trying to set `always-on` on the Drawing and Markup layer as a test.
I have tried map-source->param, and map-source->layer->param, (and earlier map-source['always-on'], and  map-source->layer['always-on]).

**Comment by klassenjs** [comment]
For the record: I see it working properly with the internal layers.

**Comment by theduckylittle** [comment]
The catalog doesn't honour it as we were trying to fix the trackers.  Adding a "lock" to the catalog could get ... interesting particularly if you had mixed always-on and non always-on layers.

**Comment by klassenjs** [comment]
My test was if it removed from tracking, I didn't think to test the catalog.

**Comment by theduckylittle** [comment]
I have updated comments in the ticket.  But the syntax I suggest was wrong it's `<param name="always-on" value="true"/>` and there is an update to also check the value with `parseBoolean` if a straight boolean test does not pass.

**Comment by klassenjs** [comment]
Does using param this way confuse what gets sent to configure the layer in OL/WMS?  I know it was more or less a pass through in the old days, don't know about in GM3.

**Comment by theduckylittle** [comment]
Yeah, it still is basically a pass through for the WMS-style layers.  We could add another section like "option" or "conf" if we really need to. The scope of the ticket was to fix this for internal layers, so we could um... not document this as recommended for the mapbook.

**Comment by klassenjs** [comment]
Could move it to yet another attribute too.  But the confusion of <param> thing bothers me.

**Comment by klassenjs** [comment]
No mapbook support and fixing the docs would be valid for now too. But I don't like overloading `param`.

**Comment by theduckylittle** [comment]
I've moved the "always-on" from "params" to "options".  If at some point we decide to move that to the mapbook we can.  Either by implementing a "<option>" parser or by mapping attributes to the options object.

**Pull request merged**
