### PR TITLE
Adding more helpful text.

### PR DESCRIPTION
**Pull request by theduckylittle**
1. Added messages to the Visible and Favorites tabs
   explaining what they are.
2. Used the new "info-box" style for the info during the empty
   super tab.
3. Added help text to the print dialog for when there are
   unprintable layers.

### CODE REVIEW

**Comment by theduckylittle** [comment]
refs: #160 -- adds help text for when there are missing layers from the print.

**Comment by theduckylittle** [comment]
Also, I'm aware there is an icon that won't render.  That'll magically pop in when #167 is merged.

**Comment by klassenjs** [comment]
I feel this is useful the first time and maybe as a reminder, but that it takes up a lot of screen real estate after the user is acquainted with the app.

**Comment by theduckylittle** [comment]
Having obvious help, IMO, is better than leaving folks stranded.  If an admin wants to turn off the help text in those two places they can do so in CSS:
```css
.visible-layers .info-box, .favorites .info-box {
 display: none;
}
```

**Comment by klassenjs** [comment]
I wasn't thinking admin turning it off.  I was thinking either the user can hide it.  I suppose if the list is long it will be scrollable anyway so probably not a big deal.

**Pull request merged**
