### PR TITLE
Ensure measure has a default tool

### PR DESCRIPTION
**Pull request by theduckylittle**
Defaults the measure tool to a polygon.

### CODE REVIEW

**Comment by klassenjs** [comment]
Should the default be `line` (so as to not change behavior if the user leaves it un-configured)?  Otherwise looks fine.

**Comment by elil** [comment]
Measure defaulting to line seems reasonable to me
________________________________

**Comment by klassenjs** [comment]
Back to @theduckylittle to merge/edit/whatever.

**Comment by elil** [comment]
Defaulting to other types is fine too if there is a reason for it.  Only mild preference for line since that is what I measure most and maybe previous defaults were.
________________________________

**Comment by tchaddad** [comment]
+1 for defaulting to line so as not to change behaviour

**Comment by theduckylittle** [comment]
Is back to line...

**Comment by klassenjs** [comment]
It looks like the "Fix tests" commit broke tests.

**Comment by theduckylittle** [comment]
Yeah, I was doing some testing in different branches and a local merge got pushed that wasn't complete. Everything is passing now and I've cleaned up the git history.

**Comment by theduckylittle** [comment]
Also, screen shot for posterity of changes. I updated the styling to fit in with more of the application:

image

**Pull request merged**
