### PR TITLE
Add browserstack notice

### PR DESCRIPTION
**Pull request by theduckylittle**
Requires for browserstack open-source tier TOS.

### CODE REVIEW

**Comment by klassenjs** [comment]
Are we allowed to freely redistribute the browser stack logo file?

**Comment by theduckylittle** [comment]
They sent me an email saying "Add this attached logo to your GitHub page."

**Comment by klassenjs** [comment]
Right.  And I'd argue that is better than a live link off site.  But by adding it we are basically saying it is ours and MIT licensed.

**Comment by klassenjs** [comment]
Adding it to the code repo that is.

**Comment by theduckylittle** [comment]
Closing in favor of: https://github.com/geomoose/geomoose-website/pull/9

**Pull request closed without merging**
