### PR TITLE
Add "Buffer All" functionality

### PR DESCRIPTION
**Pull request by theduckylittle**
Adds a new "Buffer All" tool to the Super Tab results
when configured.

Bonus! Fixes bug with buffer-select not showing grid
results.

### CODE REVIEW

**Comment by chughes-lincoln** [comment]
I've tested this out on my build and everything is working great. This, combined with the ability to buffer from a single result, may for the most part address https://github.com/geomoose/gm3/issues/365. The default buffer tool can do some more advanced things like buffering a sketch, or buffering a subset of your results, which still isn't very intuitive to the average user, but I think there are now relatively straightforward ways for admins to configure simple buffer applications.

**Comment by klassenjs** [comment]
It appears this broke Search Parcels -> Owner: Smith -> Go causes a JS error

**Comment by chughes-lincoln** [comment]
Not sure how I missed the search not working. I'm also having issues with larger buffers. On my build of the demo,
I selected around 300 parcels and tried to create a 10 foot buffer, which returned no results.

**Comment by theduckylittle** [comment]
Fixed the search error. The search service itself also had some crusty code which has been updated.

@chughes-lincoln - We look to be hitting a limit in MapServer:
```
msOWSPreParseRequest(): OWS error. XML parsing error: Excessive depth in document: 256 use XML_PARSE_HUGE option
````

**Pull request merged**
