### PR TITLE
Fixing buffer and scale distances

### PR DESCRIPTION
**Pull request by theduckylittle**
1. Fixed the buffer calculation by doing the manual
   conversions in/out of traverse mercator.
2. Added the ability to enable openlayers scaleline
   indicator which was also correctly 'measuring' the
   distance represented on the map.
2b. I added a config reducer as a catch-all of app settings that
    may not necessarily be best interpreted by the mapbook.
    This may be fluid and should likely allow the user to change
    settings if a developer gets ambitious.
3. Dropped the misleading mapserver scalelines from the
   desktop demo mapbook.

### CODE REVIEW

**Comment by theduckylittle** [comment]
@tchaddad - For some reason I can't make you a reviewer but I'd like you to see this!!!

**Comment by tchaddad** [comment]
Nice - will check it out!

**Comment by elil** [comment]
Do we still do refs: #361 and #366?  (That might give someone on the issue a ping.)

**Comment by theduckylittle** [comment]
Thanks for catching the refs @elil !!! Those are the bugs I'm trying to address with this PR. I feel a little bad roping the scalebars into the buffer fix but these issues highlight each other and I wanted them fixed at the same time.

**Comment by klassenjs** [comment]
Scale line looks good.  Probably should document switching it to metric (even though it appears trivial in app.js).  Buffer looks much better.  A buffer of 5280ft from a point on a property line corner lands on property lines rather than overshooting it.  I still stress that this is a (much better) approximation, but 3857 is still not a good projection to use for accurate measurements.

Old:
old


New:
new

**Comment by klassenjs** [comment]
#362 is also affected by this.

**Pull request merged**
